runtime: python37

handlers:
- url: /.*
  static_files: index.html
  upload: index.html

- url: /style.css
  static_files: style.css
  upload: style.css

- url: /.*\.(gif|png|jpg|jpeg|ico|svg|js|css)$
  static_files: \1
  upload: (.*\.(gif|png|jpg|jpeg|ico|svg|js|css))$

skip_files:
- ^(?!index\.html|style\.css$)
